language: java
jdk: openjdk8
script: 
  - name: Generate Auto Tests
    run: mvn compile evosuite:generate evosuite:export

  - name: Build with Maven
    run: mvn clean test

  - name: Generate JaCoCo Badge
    uses: cicirello/jacoco-badge-generator@v2
    with:
      generate-branches-badge: true
